{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ezzenix.mcverify",
    "module": "mcverify",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mcverify-0.1.0.jar",
          "url": "mcverify-0.1.0.jar",
          "size": 58997,
          "sha512": "7792a1f1eec579caa5f0905f1b041c433392bd71c23376c82978476e355bc4b28f7fe1e8511f43dcd6200367138e4710ff9f79491152e20169ed672c5ee2bf5f",
          "sha256": "682625662aacf9f3517d05e9491b015ce24f61c0781bd8a6e4b76483980c7d80",
          "sha1": "e62142073a3e005c0f18627d8836a0ee017a9626",
          "md5": "5f80e29968b2814008bd722ae70467ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "mcverify-0.1.0.jar",
          "url": "mcverify-0.1.0.jar",
          "size": 58997,
          "sha512": "7792a1f1eec579caa5f0905f1b041c433392bd71c23376c82978476e355bc4b28f7fe1e8511f43dcd6200367138e4710ff9f79491152e20169ed672c5ee2bf5f",
          "sha256": "682625662aacf9f3517d05e9491b015ce24f61c0781bd8a6e4b76483980c7d80",
          "sha1": "e62142073a3e005c0f18627d8836a0ee017a9626",
          "md5": "5f80e29968b2814008bd722ae70467ba"
        }
      ]
    }
  ]
}
