{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ezzenix.mcverify",
    "module": "mcverify",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mcverify-0.1.0.jar",
          "url": "mcverify-0.1.0.jar",
          "size": 55538,
          "sha512": "feb7d8538c6520a72b60dc59b0e458f2ae8e1ae2a19c165b77bc6ace7b11ea398df729c4098ad3a85e8f0583700df2a6294c2f11599791283e4448a91f6015da",
          "sha256": "6bde1c36087a42f8900f36d272b4f1ba335c1eb8daada27649316098a6670cc6",
          "sha1": "1dbfafee586174ee5324875261d6e02b5540d9f4",
          "md5": "1f117b9d989a8766b51628f122ed670a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "mcverify-0.1.0.jar",
          "url": "mcverify-0.1.0.jar",
          "size": 55538,
          "sha512": "feb7d8538c6520a72b60dc59b0e458f2ae8e1ae2a19c165b77bc6ace7b11ea398df729c4098ad3a85e8f0583700df2a6294c2f11599791283e4448a91f6015da",
          "sha256": "6bde1c36087a42f8900f36d272b4f1ba335c1eb8daada27649316098a6670cc6",
          "sha1": "1dbfafee586174ee5324875261d6e02b5540d9f4",
          "md5": "1f117b9d989a8766b51628f122ed670a"
        }
      ]
    }
  ]
}
