{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ezzenix.mcverify",
    "module": "mcverify",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mcverify-0.1.0.jar",
          "url": "mcverify-0.1.0.jar",
          "size": 58891,
          "sha512": "005564511834cfcf82eec45f877e9df33e496e625a0164b689f492109b261de5db758566596643f4a78cd2e105e81e9bd165ffad255e49026f1a6e809897f70d",
          "sha256": "c2e637af14721b7046c2e5787f2bc9764428502cb9d36aefcdde5c9f9251b881",
          "sha1": "9f4e92004351f762d69e516b460bb68583af52b9",
          "md5": "ed33c86f11341271468fa1c8c4f1aaa8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "mcverify-0.1.0.jar",
          "url": "mcverify-0.1.0.jar",
          "size": 58891,
          "sha512": "005564511834cfcf82eec45f877e9df33e496e625a0164b689f492109b261de5db758566596643f4a78cd2e105e81e9bd165ffad255e49026f1a6e809897f70d",
          "sha256": "c2e637af14721b7046c2e5787f2bc9764428502cb9d36aefcdde5c9f9251b881",
          "sha1": "9f4e92004351f762d69e516b460bb68583af52b9",
          "md5": "ed33c86f11341271468fa1c8c4f1aaa8"
        }
      ]
    }
  ]
}
