{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ezzenix.mcverify",
    "module": "mcverify",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mcverify-0.1.1.jar",
          "url": "mcverify-0.1.1.jar",
          "size": 59846,
          "sha512": "13b5e1169e1141c1d4c032edf71184fa6fd6e54fa8dc85b17b8c99ff11638cce89ba6af7bb34663376aa2799c0090a239c7c5901921e6d8634ff011cad61f108",
          "sha256": "a20aae22d73e2a7a52936855320078d57e4567836d6df74074ebfcfc835b55bd",
          "sha1": "e0df0a9974e9359e7e152ad2a6c86b94bdf44837",
          "md5": "a079fc3545d5252b26a3de84df4b2551"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "mcverify-0.1.1.jar",
          "url": "mcverify-0.1.1.jar",
          "size": 59846,
          "sha512": "13b5e1169e1141c1d4c032edf71184fa6fd6e54fa8dc85b17b8c99ff11638cce89ba6af7bb34663376aa2799c0090a239c7c5901921e6d8634ff011cad61f108",
          "sha256": "a20aae22d73e2a7a52936855320078d57e4567836d6df74074ebfcfc835b55bd",
          "sha1": "e0df0a9974e9359e7e152ad2a6c86b94bdf44837",
          "md5": "a079fc3545d5252b26a3de84df4b2551"
        }
      ]
    }
  ]
}
